---
ID: "0c6ce43c-7228-4f35-a6ef-302fd05b2044"
Parent: "1226c3c7-2d1f-48f5-87b4-c1da459f05e5"
Template: "1226c3c7-2d1f-48f5-87b4-c1da459f05e5"
Path: /sitecore/templates/Project/Verticals/Financial/Content Page/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: 
- ID: "c7c26117-dbb1-42b2-ab5e-f7223845cca3"
  Hint: __Thumbnail
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6cb450bc-50f0-4b68-8a4e-6971822ab2a9"
