---
ID: "b6e8084a-e0e2-4b2e-bbb9-11222edf6b35"
Parent: "57f2e85d-d695-4e6c-8c89-947ce5443e2e"
Template: "1226c3c7-2d1f-48f5-87b4-c1da459f05e5"
Path: /sitecore/content/Verticals/Services/Home/Services
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 150
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Services
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "00a8349e-2a48-494f-821d-2c8dd16efe42"
